# Generated by Django 4.2.6 on 2023-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CEO_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('number_of_branches', models.IntegerField()),
                ('number_of_employees', models.IntegerField()),
            ],
        ),
    ]
